Search 1
yjwangit/NationalParks pull request #2
Opened 2021-04-29 23:14 UTC by yjwangit

Created a Search component

2021-04-29 23:46 UTC, Pidgett reviewed
Base components for your app look great! Before merging ask your technical mentor where to place your index.css and how to configure prettier extension to get rid of those compiler errors.

2021-05-03 02:18 UTC, behnam requested changes

2021-05-03 02:18 UTC, behnam commented on server/server.mjs
> +//developer.nps.gov/api/v1/parks?parkCode=&parkCode=&stateCode=&sort=&api_key=DfbkVVqO5eM8F7cPXqbJVfOmFEHtfmBXsuktlP48
A h/u (heads-up) that you have your private key (`api_key`) being exposed to the public here.

2021-05-03 02:18 UTC, behnam commented on app/src/components/Selection.js
> +    },
This looks like the kind of data you could even put into its own file, maybe even call it a `json` file, since it's just data and no algorithm.

2021-05-05 17:24 UTC, merged